name: Python Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: pip install flake8 black

      - name: Lint code
        run: flake8 .

      - name: Format code
        run: black .

      - name: Fail if there are linting errors
        if: steps.lint.outcome == 'failure'
        run: exit 1
