name: Python Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Format code with black and lint check with flake8
        run: |
          black .
          flake8 .

      - name: Fail if there are linting errors
        if: steps.lint.outcome == 'failure'
        run: exit 1

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git fetch --no-tags origin main:temp-branch
          git add .
          git commit -m "Auto-format code with black"
          git push origin temp-branch
